### ISSUE TITLE
Readme  in detail And Dadaset.

### ISSUE THREAD

**Issue by zhangqinghua1008** [histocartography/seg-gini#1]
Hello, I'm very interested in your work. I want to reproduce them. But I don't know what order to operate, so could you please write readme in detail?
And there is no "image_labels. CSV" in the sicapv2 dataset, so I don't know how to reproduce your paper well.

**Comment by PushpakPati** [comment]
Hello, The repository will be completed soon, likely in a week. 
Please stay tuned.

**Comment by zhangqinghua1008** [comment]
OK, thank you for your reply and wait for your latest version~

By the way, I have successfully run "create_sicap_data. py". However, this error will be reported when running "preprocess. py": "[previous line repeated 993 more times] recursionerror: maximum recursion depth exceeded", and it will fall into an endless loop.
Through my debug, the problem is locked in the part of "e. extract features". I would like to ask if you encounter such a problem during processing. If so, how do you solve it?

**Comment by zhangqinghua1008** [comment]
Hi bro, do you have any new submissions?

**Comment by PushpakPati** [comment]
Hi. sorry for the delay.

The README is now up-to-date. 
We did not have any issue in creating the dataset as you have mentioned. 

You can directly download the stitched WSIs and corresponding segmentation masks from (https://ibm.ent.box.com/folder/159084721005). Link is also available on the README.

**Comment by SuooL** [comment]
Hello, the data address you provided requires a dedicated account to download. Can you provide the address of Google Drive or OneDrive?
